version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: always

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env